import re
import unicodedata


def normalizar_palabra(texto):
    texto = str(texto or "").strip().lower()
    texto = unicodedata.normalize("NFD", texto)
    texto = "".join(letra for letra in texto if unicodedata.category(letra) != "Mn")
    return texto


DICCIONARIO_HEBREO = [
    {
        "palabra": "Jehova",
        "hebreo": "יהוה",
        "transliteracion": "YHWH / Yahweh",
        "significado": "El que es; el Eterno; nombre del Senor.",
        "descripcion": "Nombre sagrado de Dios en el texto hebreo. En Reina-Valera suele aparecer como Jehova.",
        "aliases": ["Jehova", "Jehová", "Jah", "Yahweh", "Yahveh"],
    },
    {
        "palabra": "Aleluya",
        "hebreo": "הללו־יה",
        "transliteracion": "Hallelu-Yah",
        "significado": "Alabad a Jah / alabad al Senor.",
        "descripcion": "Expresion hebrea de adoracion y alabanza.",
        "aliases": ["Aleluya", "Alleluya"],
    },
    {
        "palabra": "Amen",
        "hebreo": "אמן",
        "transliteracion": "Amen",
        "significado": "Verdad; firme; asi sea.",
        "descripcion": "Expresion de confirmacion, fidelidad y acuerdo delante de Dios.",
        "aliases": ["Amen", "Amén"],
    },
    {
        "palabra": "Hosanna",
        "hebreo": "הושיעה נא",
        "transliteracion": "Hoshia na",
        "significado": "Salva ahora, te rogamos.",
        "descripcion": "Clamor de salvacion y alabanza usado en la entrada triunfal.",
        "aliases": ["Hosanna", "Hosana"],
    },
    {
        "palabra": "Rabí",
        "hebreo": "רבי",
        "transliteracion": "Rabbi",
        "significado": "Mi maestro.",
        "descripcion": "Titulo de respeto para un maestro espiritual.",
        "aliases": ["Rabi", "Rabí", "Rabboni", "Raboni"],
    },
    {
        "palabra": "Mesias",
        "hebreo": "משיח",
        "transliteracion": "Mashiaj",
        "significado": "Ungido.",
        "descripcion": "Titulo hebreo del Ungido prometido por Dios.",
        "aliases": ["Mesias", "Mesías", "Mashiaj", "Mesiás"],
    },
    {
        "palabra": "Emanuel",
        "hebreo": "עמנו אל",
        "transliteracion": "Immanu El",
        "significado": "Dios con nosotros.",
        "descripcion": "Nombre profetico asociado al nacimiento del Mesias.",
        "aliases": ["Emanuel", "Emmanuel"],
    },
    {
        "palabra": "Sion",
        "hebreo": "ציון",
        "transliteracion": "Tsiyyon",
        "significado": "Sion; monte o ciudad escogida.",
        "descripcion": "Nombre biblico vinculado a Jerusalen, al pueblo de Dios y a su monte santo.",
        "aliases": ["Sion", "Sión"],
    },
    {
        "palabra": "Eden",
        "hebreo": "עדן",
        "transliteracion": "Eden",
        "significado": "Delicia; placer; lugar de deleite.",
        "descripcion": "Nombre del jardin donde Dios puso al hombre al principio.",
        "aliases": ["Eden", "Edén"],
    },
    {
        "palabra": "Satanas",
        "hebreo": "שטן",
        "transliteracion": "Satan",
        "significado": "Adversario; acusador.",
        "descripcion": "Nombre usado para el enemigo y acusador.",
        "aliases": ["Satanas", "Satanás", "Satan"],
    },
    {
        "palabra": "Querubin",
        "hebreo": "כרוב",
        "transliteracion": "Keruv",
        "significado": "Ser celestial asociado a la presencia y gloria de Dios.",
        "descripcion": "En plural, querubines. Aparecen guardando lugares santos y ligados al arca.",
        "aliases": ["Querubin", "Querubín", "Querubines"],
    },
    {
        "palabra": "Serafin",
        "hebreo": "שרף",
        "transliteracion": "Saraf",
        "significado": "Ardiente.",
        "descripcion": "Ser celestial mencionado en la vision de Isaias.",
        "aliases": ["Serafin", "Serafín", "Serafines"],
    },
    {
        "palabra": "Abba",
        "hebreo": "אבא",
        "transliteracion": "Abba",
        "significado": "Padre.",
        "descripcion": "Termino de cercania filial usado en oracion a Dios.",
        "aliases": ["Abba"],
    },
    {
        "palabra": "Maranata",
        "hebreo": "מרנא תא",
        "transliteracion": "Maranatha",
        "significado": "El Senor viene / ven, Senor.",
        "descripcion": "Expresion aramea usada por la iglesia primitiva.",
        "aliases": ["Maranata", "Maranatha"],
    },
    {
        "palabra": "Golgota",
        "hebreo": "גלגלתא",
        "transliteracion": "Golgotha",
        "significado": "Lugar de la calavera.",
        "descripcion": "Nombre del lugar donde fue crucificado Jesus.",
        "aliases": ["Golgota", "Gólgota"],
    },
    {
        "palabra": "Elí",
        "hebreo": "אלי",
        "transliteracion": "Eli",
        "significado": "Dios mio.",
        "descripcion": "Parte del clamor: Eli, Eli, lama sabactani.",
        "aliases": ["Eli", "Elí", "Eloi", "Eloí"],
    },
    {
        "palabra": "Sabactani",
        "hebreo": "שבקתני",
        "transliteracion": "Shabaqtani",
        "significado": "Me has desamparado.",
        "descripcion": "Parte del clamor de Jesus en la cruz.",
        "aliases": ["Sabactani", "Sabactaní"],
    },
]

DICCIONARIO_HEBREO.extend(
    [
        {
            "palabra": "Majano",
            "hebreo": "\u05d2\u05dc",
            "transliteracion": "Gal",
            "significado": "Monton, pila o monticulo de piedras.",
            "descripcion": "En el contexto biblico puede referirse a un monton levantado como senal o testimonio.",
            "aliases": ["Majano", "Majanos"],
        },
        {
            "palabra": "Galaad",
            "hebreo": "\u05d2\u05dc\u05e2\u05d3",
            "transliteracion": "Gilad / Gal-ed",
            "significado": "Majano o monton de testimonio.",
            "descripcion": "Nombre vinculado al testimonio levantado con piedras; tambien region al oriente del Jordan.",
            "aliases": ["Galaad", "Galeed", "Galaadita", "Galaaditas"],
        },
        {
            "palabra": "Elohim",
            "hebreo": "\u05d0\u05dc\u05d4\u05d9\u05dd",
            "transliteracion": "Elohim",
            "significado": "Dios; Dios poderoso.",
            "descripcion": "Titulo hebreo usado para Dios, especialmente en el relato de la creacion.",
            "aliases": ["Elohim"],
        },
        {
            "palabra": "Adonai",
            "hebreo": "\u05d0\u05d3\u05e0\u05d9",
            "transliteracion": "Adonai",
            "significado": "Senor; mi Senor.",
            "descripcion": "Titulo reverente usado para dirigirse a Dios.",
            "aliases": ["Adonai"],
        },
        {
            "palabra": "Shaddai",
            "hebreo": "\u05e9\u05d3\u05d9",
            "transliteracion": "Shaddai",
            "significado": "Todopoderoso.",
            "descripcion": "Titulo divino conocido en la expresion El Shaddai.",
            "aliases": ["Shaddai", "Sadai"],
        },
        {
            "palabra": "Shalom",
            "hebreo": "\u05e9\u05dc\u05d5\u05dd",
            "transliteracion": "Shalom",
            "significado": "Paz, plenitud, bienestar.",
            "descripcion": "Palabra hebrea de paz integral y armonia.",
            "aliases": ["Shalom", "Salem"],
        },
        {
            "palabra": "Sheol",
            "hebreo": "\u05e9\u05d0\u05d5\u05dc",
            "transliteracion": "Sheol",
            "significado": "Lugar de los muertos; sepulcro.",
            "descripcion": "Termino hebreo usado para el ambito de la muerte.",
            "aliases": ["Sheol", "Seol"],
        },
        {
            "palabra": "Torah",
            "hebreo": "\u05ea\u05d5\u05e8\u05d4",
            "transliteracion": "Torah",
            "significado": "Ley, instruccion, ensenanza.",
            "descripcion": "Instruccion divina; tambien nombre del conjunto de los cinco libros de Moises.",
            "aliases": ["Torah", "Tora"],
        },
        {
            "palabra": "Pesaj",
            "hebreo": "\u05e4\u05e1\u05d7",
            "transliteracion": "Pesaj",
            "significado": "Pascua; pasar por alto.",
            "descripcion": "Fiesta que recuerda la liberacion de Israel de Egipto.",
            "aliases": ["Pesaj", "Pascua"],
        },
        {
            "palabra": "Sabat",
            "hebreo": "\u05e9\u05d1\u05ea",
            "transliteracion": "Shabbat",
            "significado": "Reposo; cesar.",
            "descripcion": "Dia de descanso consagrado a Dios.",
            "aliases": ["Sabat", "Sabado", "Shabbat"],
        },
        {
            "palabra": "Jubileo",
            "hebreo": "\u05d9\u05d5\u05d1\u05dc",
            "transliteracion": "Yovel",
            "significado": "Jubileo; toque o cuerno de carnero.",
            "descripcion": "Ano especial de liberacion y restitucion en la ley de Moises.",
            "aliases": ["Jubileo", "Yovel"],
        },
        {
            "palabra": "Manna",
            "hebreo": "\u05de\u05df",
            "transliteracion": "Man",
            "significado": "¿Que es esto?",
            "descripcion": "Alimento dado por Dios a Israel en el desierto.",
            "aliases": ["Mana", "Maná", "Manna"],
        },
        {
            "palabra": "Efod",
            "hebreo": "\u05d0\u05e4\u05d5\u05d3",
            "transliteracion": "Efod",
            "significado": "Vestidura sacerdotal.",
            "descripcion": "Prenda relacionada con el servicio sacerdotal y el sumo sacerdote.",
            "aliases": ["Efod"],
        },
        {
            "palabra": "Urim",
            "hebreo": "\u05d0\u05d5\u05e8\u05d9\u05dd",
            "transliteracion": "Urim",
            "significado": "Luces.",
            "descripcion": "Elemento asociado al pectoral sacerdotal para consultar delante de Dios.",
            "aliases": ["Urim"],
        },
        {
            "palabra": "Tumim",
            "hebreo": "\u05ea\u05de\u05d9\u05dd",
            "transliteracion": "Tumim",
            "significado": "Perfecciones o integridades.",
            "descripcion": "Elemento asociado al pectoral sacerdotal junto con Urim.",
            "aliases": ["Tumim", "Thummim"],
        },
        {
            "palabra": "Belen",
            "hebreo": "\u05d1\u05d9\u05ea \u05dc\u05d7\u05dd",
            "transliteracion": "Beit Lejem",
            "significado": "Casa de pan.",
            "descripcion": "Ciudad de David y lugar asociado al nacimiento de Jesus.",
            "aliases": ["Belen", "Belén", "Bethlehem"],
        },
        {
            "palabra": "Betel",
            "hebreo": "\u05d1\u05d9\u05ea \u05d0\u05dc",
            "transliteracion": "Beit-El",
            "significado": "Casa de Dios.",
            "descripcion": "Lugar donde Jacob tuvo la vision de la escalera.",
            "aliases": ["Betel", "Bet-el", "Bethel"],
        },
        {
            "palabra": "Peniel",
            "hebreo": "\u05e4\u05e0\u05d9\u05d0\u05dc",
            "transliteracion": "Peni-El",
            "significado": "Rostro de Dios.",
            "descripcion": "Lugar donde Jacob dijo haber visto a Dios cara a cara.",
            "aliases": ["Peniel", "Penuel"],
        },
        {
            "palabra": "Moriah",
            "hebreo": "\u05de\u05e8\u05d9\u05d4",
            "transliteracion": "Moriah",
            "significado": "Visto/provisto por Jehova.",
            "descripcion": "Monte asociado al sacrificio de Isaac y al templo.",
            "aliases": ["Moriah", "Moria"],
        },
        {
            "palabra": "Horeb",
            "hebreo": "\u05d7\u05e8\u05d1",
            "transliteracion": "Jorev",
            "significado": "Sequedad, desierto.",
            "descripcion": "Monte de Dios, asociado a Moises y la revelacion divina.",
            "aliases": ["Horeb"],
        },
        {
            "palabra": "Sinai",
            "hebreo": "\u05e1\u05d9\u05e0\u05d9",
            "transliteracion": "Sinai",
            "significado": "Monte Sinai.",
            "descripcion": "Monte donde Israel recibio la ley.",
            "aliases": ["Sinai", "Sinaí"],
        },
        {
            "palabra": "Canaan",
            "hebreo": "\u05db\u05e0\u05e2\u05df",
            "transliteracion": "Kena'an",
            "significado": "Humillado, bajo, sometido.",
            "descripcion": "Nombre de la tierra prometida y de sus antiguos habitantes.",
            "aliases": ["Canaan", "Canaán", "Cananeo", "Cananeos"],
        },
        {
            "palabra": "Jerusalen",
            "hebreo": "\u05d9\u05e8\u05d5\u05e9\u05dc\u05dd",
            "transliteracion": "Yerushalayim",
            "significado": "Ciudad/fundamento de paz.",
            "descripcion": "Ciudad santa, centro espiritual e historico de Israel.",
            "aliases": ["Jerusalen", "Jerusalén", "Yerushalayim"],
        },
        {
            "palabra": "Getsemani",
            "hebreo": "\u05d2\u05ea \u05e9\u05de\u05e0\u05d9\u05dd",
            "transliteracion": "Gat Shemanim",
            "significado": "Prensa de aceite.",
            "descripcion": "Lugar donde Jesus oro antes de ser entregado.",
            "aliases": ["Getsemani", "Getsemaní", "Gethsemani"],
        },
        {
            "palabra": "Gehenna",
            "hebreo": "\u05d2\u05d9\u05d0 \u05d1\u05df \u05d4\u05e0\u05dd",
            "transliteracion": "Ge Ben-Hinnom",
            "significado": "Valle del hijo de Hinom.",
            "descripcion": "Lugar usado como imagen de juicio.",
            "aliases": ["Gehenna", "Gehena", "Hinom"],
        },
        {
            "palabra": "Silo",
            "hebreo": "\u05e9\u05d9\u05dc\u05d4",
            "transliteracion": "Shiloh",
            "significado": "Reposo o enviado.",
            "descripcion": "Lugar del tabernaculo; tambien termino mesianico segun algunas lecturas.",
            "aliases": ["Silo", "Shiloh"],
        },
        {
            "palabra": "Siloe",
            "hebreo": "\u05e9\u05dc\u05d5\u05d7",
            "transliteracion": "Shiloaj",
            "significado": "Enviado.",
            "descripcion": "Estanque mencionado en el Evangelio de Juan.",
            "aliases": ["Siloe", "Siloé"],
        },
        {
            "palabra": "Israel",
            "hebreo": "\u05d9\u05e9\u05e8\u05d0\u05dc",
            "transliteracion": "Yisrael",
            "significado": "Dios lucha / Dios prevalece.",
            "descripcion": "Nombre dado a Jacob y luego al pueblo del pacto.",
            "aliases": ["Israel", "Israelita", "Israelitas"],
        },
        {
            "palabra": "Jacob",
            "hebreo": "\u05d9\u05e2\u05e7\u05d1",
            "transliteracion": "Yaakov",
            "significado": "El que toma del talon; suplantador.",
            "descripcion": "Patriarca que recibio el nombre Israel.",
            "aliases": ["Jacob", "Jacobo", "Yaakov"],
        },
        {
            "palabra": "Abraham",
            "hebreo": "\u05d0\u05d1\u05e8\u05d4\u05dd",
            "transliteracion": "Avraham",
            "significado": "Padre de multitud.",
            "descripcion": "Patriarca llamado por Dios y padre del pueblo del pacto.",
            "aliases": ["Abraham", "Abram", "Avraham"],
        },
        {
            "palabra": "Isaac",
            "hebreo": "\u05d9\u05e6\u05d7\u05e7",
            "transliteracion": "Yitzjak",
            "significado": "Risa; el rie.",
            "descripcion": "Hijo de Abraham y Sara.",
            "aliases": ["Isaac", "Yitzjak"],
        },
        {
            "palabra": "Sara",
            "hebreo": "\u05e9\u05e8\u05d4",
            "transliteracion": "Sarah",
            "significado": "Princesa.",
            "descripcion": "Esposa de Abraham y madre de Isaac.",
            "aliases": ["Sara", "Sarai", "Sarah"],
        },
        {
            "palabra": "Moises",
            "hebreo": "\u05de\u05e9\u05d4",
            "transliteracion": "Moshe",
            "significado": "Sacado de las aguas.",
            "descripcion": "Libertador de Israel y mediador de la ley.",
            "aliases": ["Moises", "Moisés", "Moshe"],
        },
        {
            "palabra": "Josue",
            "hebreo": "\u05d9\u05d4\u05d5\u05e9\u05e2",
            "transliteracion": "Yehoshua",
            "significado": "Jehova salva.",
            "descripcion": "Nombre relacionado con Yeshua/Jesus; lider que introdujo a Israel en Canaan.",
            "aliases": ["Josue", "Josué", "Yehoshua"],
        },
        {
            "palabra": "Jesus",
            "hebreo": "\u05d9\u05e9\u05d5\u05e2",
            "transliteracion": "Yeshua",
            "significado": "Salvacion; Jehova salva.",
            "descripcion": "Nombre del Senor Jesucristo en forma hebrea/aramea.",
            "aliases": ["Jesus", "Jesús", "Yeshua"],
        },
        {
            "palabra": "David",
            "hebreo": "\u05d3\u05d5\u05d3",
            "transliteracion": "David",
            "significado": "Amado.",
            "descripcion": "Rey de Israel y autor de muchos salmos.",
            "aliases": ["David"],
        },
        {
            "palabra": "Salomon",
            "hebreo": "\u05e9\u05dc\u05de\u05d4",
            "transliteracion": "Shlomo",
            "significado": "Pacifico; de paz.",
            "descripcion": "Hijo de David, rey asociado a sabiduria y templo.",
            "aliases": ["Salomon", "Salomón", "Shlomo"],
        },
        {
            "palabra": "Samuel",
            "hebreo": "\u05e9\u05de\u05d5\u05d0\u05dc",
            "transliteracion": "Shemuel",
            "significado": "Oido por Dios / nombre de Dios.",
            "descripcion": "Profeta y juez de Israel.",
            "aliases": ["Samuel"],
        },
        {
            "palabra": "Daniel",
            "hebreo": "\u05d3\u05e0\u05d9\u05d0\u05dc",
            "transliteracion": "Daniyyel",
            "significado": "Dios es mi juez.",
            "descripcion": "Profeta llevado a Babilonia.",
            "aliases": ["Daniel"],
        },
        {
            "palabra": "Elias",
            "hebreo": "\u05d0\u05dc\u05d9\u05d4\u05d5",
            "transliteracion": "Eliyahu",
            "significado": "Mi Dios es Jehova.",
            "descripcion": "Profeta del Senor frente a la idolatria de Baal.",
            "aliases": ["Elias", "Elías", "Eliyahu"],
        },
        {
            "palabra": "Eliseo",
            "hebreo": "\u05d0\u05dc\u05d9\u05e9\u05e2",
            "transliteracion": "Elisha",
            "significado": "Dios es salvacion.",
            "descripcion": "Profeta sucesor de Elias.",
            "aliases": ["Eliseo", "Elisha"],
        },
        {
            "palabra": "Isaias",
            "hebreo": "\u05d9\u05e9\u05e2\u05d9\u05d4\u05d5",
            "transliteracion": "Yeshayahu",
            "significado": "Jehova salva.",
            "descripcion": "Profeta mayor con fuerte mensaje mesianico.",
            "aliases": ["Isaias", "Isaías", "Yeshayahu"],
        },
        {
            "palabra": "Jeremias",
            "hebreo": "\u05d9\u05e8\u05de\u05d9\u05d4\u05d5",
            "transliteracion": "Yirmeyahu",
            "significado": "Jehova levanta o establece.",
            "descripcion": "Profeta llamado antes de nacer.",
            "aliases": ["Jeremias", "Jeremías"],
        },
        {
            "palabra": "Ezequiel",
            "hebreo": "\u05d9\u05d7\u05d6\u05e7\u05d0\u05dc",
            "transliteracion": "Yejezkel",
            "significado": "Dios fortalece.",
            "descripcion": "Profeta del exilio.",
            "aliases": ["Ezequiel"],
        },
        {
            "palabra": "Zacarias",
            "hebreo": "\u05d6\u05db\u05e8\u05d9\u05d4",
            "transliteracion": "Zekharyah",
            "significado": "Jehova recuerda.",
            "descripcion": "Nombre profetico y sacerdotal.",
            "aliases": ["Zacarias", "Zacarías"],
        },
        {
            "palabra": "Malaquias",
            "hebreo": "\u05de\u05dc\u05d0\u05db\u05d9",
            "transliteracion": "Malakhi",
            "significado": "Mi mensajero.",
            "descripcion": "Ultimo profeta del Antiguo Testamento en el orden cristiano.",
            "aliases": ["Malaquias", "Malaquías"],
        },
        {
            "palabra": "Juda",
            "hebreo": "\u05d9\u05d4\u05d5\u05d3\u05d4",
            "transliteracion": "Yehudah",
            "significado": "Alabanza.",
            "descripcion": "Tribu de la cual viene David y el Mesias.",
            "aliases": ["Juda", "Judá", "Judas", "Judio", "Judios"],
        },
    ]
)


DICCIONARIO_HEBREO.extend(
    [
        {
            "palabra": "Adan",
            "hebreo": "\u05d0\u05d3\u05dd",
            "transliteracion": "Adam",
            "significado": "Hombre; humanidad; relacionado con la tierra rojiza.",
            "descripcion": "Nombre del primer hombre y termino vinculado a la humanidad.",
            "aliases": ["Adan", "Adam"],
        },
        {
            "palabra": "Eva",
            "hebreo": "\u05d7\u05d5\u05d4",
            "transliteracion": "Javah",
            "significado": "Vida; madre de los vivientes.",
            "descripcion": "Nombre dado a la primera mujer.",
            "aliases": ["Eva", "Hava", "Javah"],
        },
        {
            "palabra": "Cain",
            "hebreo": "\u05e7\u05d9\u05df",
            "transliteracion": "Qayin",
            "significado": "Adquirido; posesion.",
            "descripcion": "Primer hijo de Adan y Eva.",
            "aliases": ["Cain", "Kayin"],
        },
        {
            "palabra": "Abel",
            "hebreo": "\u05d4\u05d1\u05dc",
            "transliteracion": "Hevel",
            "significado": "Aliento; vapor.",
            "descripcion": "Hijo de Adan y Eva; pastor cuyo sacrificio fue aceptado.",
            "aliases": ["Abel", "Hevel"],
        },
        {
            "palabra": "Set",
            "hebreo": "\u05e9\u05ea",
            "transliteracion": "Shet",
            "significado": "Puesto; designado.",
            "descripcion": "Hijo de Adan y Eva dado en lugar de Abel.",
            "aliases": ["Set", "Seth", "Shet"],
        },
        {
            "palabra": "Enoc",
            "hebreo": "\u05d7\u05e0\u05d5\u05da",
            "transliteracion": "Janokh",
            "significado": "Dedicado; instruido.",
            "descripcion": "Nombre de un patriarca que camino con Dios.",
            "aliases": ["Enoc", "Enoch", "Janokh"],
        },
        {
            "palabra": "Matusalen",
            "hebreo": "\u05de\u05ea\u05d5\u05e9\u05dc\u05d7",
            "transliteracion": "Metushelaj",
            "significado": "Hombre del dardo; hombre enviado.",
            "descripcion": "Patriarca recordado por su longevidad.",
            "aliases": ["Matusalen", "Metusalen", "Metushelaj"],
        },
        {
            "palabra": "Noe",
            "hebreo": "\u05e0\u05d7",
            "transliteracion": "Noaj",
            "significado": "Descanso; consuelo.",
            "descripcion": "Patriarca preservado en el diluvio.",
            "aliases": ["Noe", "Noah", "Noaj"],
        },
        {
            "palabra": "Sem",
            "hebreo": "\u05e9\u05dd",
            "transliteracion": "Shem",
            "significado": "Nombre; renombre.",
            "descripcion": "Hijo de Noe y ancestro de pueblos semitas.",
            "aliases": ["Sem", "Shem"],
        },
        {
            "palabra": "Cam",
            "hebreo": "\u05d7\u05dd",
            "transliteracion": "Jam",
            "significado": "Caliente; ardiente.",
            "descripcion": "Hijo de Noe.",
            "aliases": ["Cam", "Ham", "Jam"],
        },
        {
            "palabra": "Jafet",
            "hebreo": "\u05d9\u05e4\u05ea",
            "transliteracion": "Yefet",
            "significado": "Ensanchamiento; belleza.",
            "descripcion": "Hijo de Noe.",
            "aliases": ["Jafet", "Japheth", "Yefet"],
        },
        {
            "palabra": "Nimrod",
            "hebreo": "\u05e0\u05de\u05e8\u05d3",
            "transliteracion": "Nimrod",
            "significado": "Rebelde; nos rebelaremos.",
            "descripcion": "Poderoso cazador asociado a Babel y reinos antiguos.",
            "aliases": ["Nimrod"],
        },
        {
            "palabra": "Babel",
            "hebreo": "\u05d1\u05d1\u05dc",
            "transliteracion": "Bavel",
            "significado": "Confusion; puerta de dios segun tradicion babilonica.",
            "descripcion": "Lugar de la torre y nombre relacionado con Babilonia.",
            "aliases": ["Babel", "Babilonia", "Babilonico", "Babilonios"],
        },
        {
            "palabra": "Ararat",
            "hebreo": "\u05d0\u05e8\u05e8\u05d8",
            "transliteracion": "Ararat",
            "significado": "Region montanosa de Armenia.",
            "descripcion": "Montes donde reposo el arca segun Genesis.",
            "aliases": ["Ararat"],
        },
        {
            "palabra": "Lot",
            "hebreo": "\u05dc\u05d5\u05d8",
            "transliteracion": "Lot",
            "significado": "Cubierta; velo.",
            "descripcion": "Sobrino de Abraham.",
            "aliases": ["Lot"],
        },
        {
            "palabra": "Rebeca",
            "hebreo": "\u05e8\u05d1\u05e7\u05d4",
            "transliteracion": "Rivqah",
            "significado": "Lazo; unir o atar.",
            "descripcion": "Esposa de Isaac y madre de Jacob y Esau.",
            "aliases": ["Rebeca", "Rebecca", "Rivqah"],
        },
        {
            "palabra": "Raquel",
            "hebreo": "\u05e8\u05d7\u05dc",
            "transliteracion": "Rajel",
            "significado": "Oveja.",
            "descripcion": "Esposa amada de Jacob y madre de Jose y Benjamin.",
            "aliases": ["Raquel", "Rachel", "Rajel"],
        },
        {
            "palabra": "Lea",
            "hebreo": "\u05dc\u05d0\u05d4",
            "transliteracion": "Leah",
            "significado": "Cansada; fatigada.",
            "descripcion": "Esposa de Jacob y madre de varias tribus de Israel.",
            "aliases": ["Lea", "Leah"],
            "solo_mayuscula": True,
        },
        {
            "palabra": "Jose",
            "hebreo": "\u05d9\u05d5\u05e1\u05e3",
            "transliteracion": "Yosef",
            "significado": "Jehova anada; Dios aumente.",
            "descripcion": "Hijo de Jacob vendido a Egipto.",
            "aliases": ["Jose", "Joseph", "Yosef"],
        },
        {
            "palabra": "Benjamin",
            "hebreo": "\u05d1\u05e0\u05d9\u05de\u05d9\u05df",
            "transliteracion": "Binyamin",
            "significado": "Hijo de la mano derecha.",
            "descripcion": "Hijo menor de Jacob y nombre de una tribu.",
            "aliases": ["Benjamin", "Benyamin", "Binyamin"],
        },
        {
            "palabra": "Ruben",
            "hebreo": "\u05e8\u05d0\u05d5\u05d1\u05df",
            "transliteracion": "Reuven",
            "significado": "Mira, un hijo.",
            "descripcion": "Primogenito de Jacob.",
            "aliases": ["Ruben", "Reuben", "Reuven"],
        },
        {
            "palabra": "Simeon",
            "hebreo": "\u05e9\u05de\u05e2\u05d5\u05df",
            "transliteracion": "Shimon",
            "significado": "Oido; Dios ha escuchado.",
            "descripcion": "Hijo de Jacob y nombre de una tribu.",
            "aliases": ["Simeon", "Simon", "Shimon"],
        },
        {
            "palabra": "Levi",
            "hebreo": "\u05dc\u05d5\u05d9",
            "transliteracion": "Levi",
            "significado": "Unido; adherido.",
            "descripcion": "Tribu sacerdotal de Israel.",
            "aliases": ["Levi", "Levita", "Levitas"],
        },
        {
            "palabra": "Dan",
            "hebreo": "\u05d3\u05df",
            "transliteracion": "Dan",
            "significado": "Juez; juzgo.",
            "descripcion": "Hijo de Jacob y nombre de una tribu.",
            "aliases": ["Dan", "Danitas"],
            "solo_mayuscula": True,
        },
        {
            "palabra": "Neftali",
            "hebreo": "\u05e0\u05e4\u05ea\u05dc\u05d9",
            "transliteracion": "Naftali",
            "significado": "Mi lucha.",
            "descripcion": "Hijo de Jacob y nombre de una tribu.",
            "aliases": ["Neftali", "Naftali"],
        },
        {
            "palabra": "Gad",
            "hebreo": "\u05d2\u05d3",
            "transliteracion": "Gad",
            "significado": "Fortuna; tropa.",
            "descripcion": "Hijo de Jacob y nombre de una tribu.",
            "aliases": ["Gad", "Gaditas"],
        },
        {
            "palabra": "Aser",
            "hebreo": "\u05d0\u05e9\u05e8",
            "transliteracion": "Asher",
            "significado": "Feliz; dichoso.",
            "descripcion": "Hijo de Jacob y nombre de una tribu.",
            "aliases": ["Aser", "Asher"],
        },
        {
            "palabra": "Isacar",
            "hebreo": "\u05d9\u05e9\u05e9\u05db\u05e8",
            "transliteracion": "Yissajar",
            "significado": "Hay recompensa.",
            "descripcion": "Hijo de Jacob y nombre de una tribu.",
            "aliases": ["Isacar", "Issachar", "Yissajar"],
        },
        {
            "palabra": "Zabulon",
            "hebreo": "\u05d6\u05d1\u05d5\u05dc\u05df",
            "transliteracion": "Zevulun",
            "significado": "Morada; habitacion.",
            "descripcion": "Hijo de Jacob y nombre de una tribu.",
            "aliases": ["Zabulon", "Zebulon", "Zevulun"],
        },
        {
            "palabra": "Efraim",
            "hebreo": "\u05d0\u05e4\u05e8\u05d9\u05dd",
            "transliteracion": "Efrayim",
            "significado": "Doble fruto; fructifero.",
            "descripcion": "Hijo de Jose y nombre tribal importante.",
            "aliases": ["Efraim", "Ephraim", "Efrayim"],
        },
        {
            "palabra": "Manases",
            "hebreo": "\u05de\u05e0\u05e9\u05d4",
            "transliteracion": "Menashe",
            "significado": "El que hace olvidar.",
            "descripcion": "Hijo de Jose y nombre de una media tribu.",
            "aliases": ["Manases", "Manasseh", "Menashe"],
        },
        {
            "palabra": "Esau",
            "hebreo": "\u05e2\u05e9\u05d5",
            "transliteracion": "Esav",
            "significado": "Velludo; hecho.",
            "descripcion": "Hermano de Jacob y antepasado de Edom.",
            "aliases": ["Esau", "Esav"],
        },
        {
            "palabra": "Edom",
            "hebreo": "\u05d0\u05d3\u05d5\u05dd",
            "transliteracion": "Edom",
            "significado": "Rojo.",
            "descripcion": "Nombre dado a Esau y a su pueblo.",
            "aliases": ["Edom", "Edomita", "Edomitas"],
        },
        {
            "palabra": "Moab",
            "hebreo": "\u05de\u05d5\u05d0\u05d1",
            "transliteracion": "Moav",
            "significado": "De su padre.",
            "descripcion": "Pueblo descendiente de Lot.",
            "aliases": ["Moab", "Moabita", "Moabitas"],
        },
        {
            "palabra": "Amon",
            "hebreo": "\u05e2\u05de\u05d5\u05df",
            "transliteracion": "Ammon",
            "significado": "Pueblo; pariente.",
            "descripcion": "Pueblo descendiente de Lot.",
            "aliases": ["Amon", "Amonita", "Amonitas", "Ammon"],
        },
        {
            "palabra": "Amalec",
            "hebreo": "\u05e2\u05de\u05dc\u05e7",
            "transliteracion": "Amaleq",
            "significado": "Pueblo que lame / trabajador; significado discutido.",
            "descripcion": "Pueblo enemigo de Israel en el desierto.",
            "aliases": ["Amalec", "Amalecita", "Amalecitas"],
        },
        {
            "palabra": "Filistea",
            "hebreo": "\u05e4\u05dc\u05e9\u05ea",
            "transliteracion": "Peleshet",
            "significado": "Tierra de peregrinos o invasores.",
            "descripcion": "Region de los filisteos.",
            "aliases": ["Filistea", "Filisteo", "Filisteos"],
        },
        {
            "palabra": "Jordan",
            "hebreo": "\u05d9\u05e8\u05d3\u05df",
            "transliteracion": "Yarden",
            "significado": "El que desciende.",
            "descripcion": "Rio principal asociado al paso de Israel y al bautismo de Jesus.",
            "aliases": ["Jordan", "Jordano", "Yarden"],
        },
        {
            "palabra": "Nilo",
            "hebreo": "\u05d9\u05d0\u05e8",
            "transliteracion": "Yeor",
            "significado": "Rio; canal.",
            "descripcion": "Rio de Egipto mencionado en el relato del Exodo.",
            "aliases": ["Nilo", "Yeor"],
        },
        {
            "palabra": "Eufrates",
            "hebreo": "\u05e4\u05e8\u05ea",
            "transliteracion": "Perat",
            "significado": "Fructifero; rio ancho.",
            "descripcion": "Gran rio de Mesopotamia mencionado desde Genesis.",
            "aliases": ["Eufrates", "Perat"],
        },
        {
            "palabra": "Hidekel",
            "hebreo": "\u05d7\u05d3\u05e7\u05dc",
            "transliteracion": "Jideqel",
            "significado": "Tigris.",
            "descripcion": "Rio mencionado en Genesis, identificado comunmente con el Tigris.",
            "aliases": ["Hidekel", "Tigris", "Jideqel"],
        },
        {
            "palabra": "Pison",
            "hebreo": "\u05e4\u05d9\u05e9\u05d5\u05df",
            "transliteracion": "Pishon",
            "significado": "Dispersarse; fluir libremente.",
            "descripcion": "Uno de los rios asociados al Eden.",
            "aliases": ["Pison", "Pishon"],
        },
        {
            "palabra": "Gihon",
            "hebreo": "\u05d2\u05d9\u05d7\u05d5\u05df",
            "transliteracion": "Gijon",
            "significado": "Brota; manantial que irrumpe.",
            "descripcion": "Rio de Eden y tambien fuente cercana a Jerusalen.",
            "aliases": ["Gihon", "Gijon"],
        },
        {
            "palabra": "Hermon",
            "hebreo": "\u05d7\u05e8\u05de\u05d5\u05df",
            "transliteracion": "Jermon",
            "significado": "Consagrado; dedicado.",
            "descripcion": "Monte del norte de Israel.",
            "aliases": ["Hermon", "Jermon"],
        },
        {
            "palabra": "Carmelo",
            "hebreo": "\u05db\u05e8\u05de\u05dc",
            "transliteracion": "Karmel",
            "significado": "Vina de Dios; jardin fructifero.",
            "descripcion": "Monte asociado al profeta Elias.",
            "aliases": ["Carmelo", "Karmel"],
        },
        {
            "palabra": "Tabor",
            "hebreo": "\u05ea\u05d1\u05d5\u05e8",
            "transliteracion": "Tavor",
            "significado": "Altura; monticulo.",
            "descripcion": "Monte de Galilea mencionado en la Biblia.",
            "aliases": ["Tabor", "Tavor"],
        },
        {
            "palabra": "Libano",
            "hebreo": "\u05dc\u05d1\u05e0\u05d5\u05df",
            "transliteracion": "Levanon",
            "significado": "Blanco.",
            "descripcion": "Region montanosa famosa por sus cedros.",
            "aliases": ["Libano", "Lebanon", "Levanon"],
        },
        {
            "palabra": "Hebron",
            "hebreo": "\u05d7\u05d1\u05e8\u05d5\u05df",
            "transliteracion": "Jevron",
            "significado": "Asociacion; alianza; comunion.",
            "descripcion": "Ciudad patriarcal relacionada con Abraham y David.",
            "aliases": ["Hebron", "Jebron", "Jevron"],
        },
        {
            "palabra": "Jerico",
            "hebreo": "\u05d9\u05e8\u05d9\u05d7\u05d5",
            "transliteracion": "Yerijo",
            "significado": "Ciudad de la luna o de fragancia; significado discutido.",
            "descripcion": "Ciudad conquistada por Israel al entrar en Canaan.",
            "aliases": ["Jerico", "Yerijo"],
        },
        {
            "palabra": "Nazaret",
            "hebreo": "\u05e0\u05e6\u05e8\u05ea",
            "transliteracion": "Natzeret",
            "significado": "Rama; guardada; significado discutido.",
            "descripcion": "Ciudad donde crecio Jesus.",
            "aliases": ["Nazaret", "Nazareth", "Natzeret"],
        },
        {
            "palabra": "Galilea",
            "hebreo": "\u05d2\u05dc\u05d9\u05dc",
            "transliteracion": "Galil",
            "significado": "Distrito; region; circulo.",
            "descripcion": "Region del norte vinculada al ministerio de Jesus.",
            "aliases": ["Galilea", "Galil", "Galileo", "Galileos"],
        },
        {
            "palabra": "Samaria",
            "hebreo": "\u05e9\u05de\u05e8\u05d5\u05df",
            "transliteracion": "Shomron",
            "significado": "Atalaya; lugar de vigilancia.",
            "descripcion": "Ciudad y region del reino del norte.",
            "aliases": ["Samaria", "Samaritano", "Samaritanos", "Shomron"],
        },
        {
            "palabra": "Judea",
            "hebreo": "\u05d9\u05d4\u05d5\u05d3\u05d4",
            "transliteracion": "Yehudah",
            "significado": "Alabanza.",
            "descripcion": "Region vinculada a Juda.",
            "aliases": ["Judea", "Judah", "Judeo", "Judeos"],
        },
        {
            "palabra": "Egipto",
            "hebreo": "\u05de\u05e6\u05e8\u05d9\u05dd",
            "transliteracion": "Mitzrayim",
            "significado": "Doble estrechez; tierra de angostura.",
            "descripcion": "Lugar de esclavitud y liberacion de Israel.",
            "aliases": ["Egipto", "Egipcio", "Egipcios", "Mitzrayim"],
        },
        {
            "palabra": "Asiria",
            "hebreo": "\u05d0\u05e9\u05d5\u05e8",
            "transliteracion": "Ashur",
            "significado": "Llanura; nombre del pueblo asirio.",
            "descripcion": "Imperio que llevo cautivo al reino del norte.",
            "aliases": ["Asiria", "Asirio", "Asirios", "Asur", "Ashur"],
        },
        {
            "palabra": "Damasco",
            "hebreo": "\u05d3\u05de\u05e9\u05e7",
            "transliteracion": "Damesek",
            "significado": "Ciudad antigua de Siria; significado discutido.",
            "descripcion": "Capital siria mencionada en ambos testamentos.",
            "aliases": ["Damasco", "Damesek"],
        },
        {
            "palabra": "Tiro",
            "hebreo": "\u05e6\u05d5\u05e8",
            "transliteracion": "Tzor",
            "significado": "Roca.",
            "descripcion": "Ciudad fenicia costera.",
            "aliases": ["Tiro", "Tzor"],
        },
        {
            "palabra": "Sidon",
            "hebreo": "\u05e6\u05d9\u05d3\u05d5\u05df",
            "transliteracion": "Tzidon",
            "significado": "Pesca; lugar de pesca.",
            "descripcion": "Ciudad fenicia mencionada junto a Tiro.",
            "aliases": ["Sidon", "Tzidon"],
        },
        {
            "palabra": "Berseba",
            "hebreo": "\u05d1\u05d0\u05e8 \u05e9\u05d1\u05e2",
            "transliteracion": "Be'er Sheva",
            "significado": "Pozo del juramento; pozo de siete.",
            "descripcion": "Lugar patriarcal al sur de la tierra.",
            "aliases": ["Berseba", "Beerseba", "Beer Sheba", "Beer Sheva"],
        },
        {
            "palabra": "Mizpa",
            "hebreo": "\u05de\u05e6\u05e4\u05d4",
            "transliteracion": "Mitzpah",
            "significado": "Atalaya; puesto de vigilancia.",
            "descripcion": "Nombre de varios lugares biblicos.",
            "aliases": ["Mizpa", "Mizpe", "Mitzpah"],
        },
        {
            "palabra": "Gilgal",
            "hebreo": "\u05d2\u05dc\u05d2\u05dc",
            "transliteracion": "Gilgal",
            "significado": "Rueda; circulo; rodar.",
            "descripcion": "Lugar asociado a la entrada de Israel en Canaan.",
            "aliases": ["Gilgal"],
        },
        {
            "palabra": "Rama",
            "hebreo": "\u05e8\u05de\u05d4",
            "transliteracion": "Ramah",
            "significado": "Altura.",
            "descripcion": "Nombre de varias ciudades altas.",
            "aliases": ["Rama", "Ramah"],
            "solo_mayuscula": True,
        },
        {
            "palabra": "Meguido",
            "hebreo": "\u05de\u05d2\u05d3\u05d5",
            "transliteracion": "Megiddo",
            "significado": "Lugar de tropas; reunion.",
            "descripcion": "Ciudad estrategica asociada a batallas.",
            "aliases": ["Meguido", "Megido", "Megiddo"],
        },
        {
            "palabra": "Caleb",
            "hebreo": "\u05db\u05dc\u05d1",
            "transliteracion": "Kalev",
            "significado": "Perro; tambien entendido como fiel/de todo corazon.",
            "descripcion": "Espia fiel que animo a entrar en la tierra prometida.",
            "aliases": ["Caleb", "Kalev"],
        },
        {
            "palabra": "Gedeon",
            "hebreo": "\u05d2\u05d3\u05e2\u05d5\u05df",
            "transliteracion": "Gid'on",
            "significado": "Cortador; derribador.",
            "descripcion": "Juez de Israel usado para librar al pueblo de Madian.",
            "aliases": ["Gedeon", "Gideon"],
        },
        {
            "palabra": "Sansón",
            "hebreo": "\u05e9\u05de\u05e9\u05d5\u05df",
            "transliteracion": "Shimshon",
            "significado": "Como el sol; solar.",
            "descripcion": "Juez de Israel conocido por su fuerza.",
            "aliases": ["Sanson", "Samson", "Shimshon"],
        },
        {
            "palabra": "Rut",
            "hebreo": "\u05e8\u05d5\u05ea",
            "transliteracion": "Rut",
            "significado": "Amiga; companera.",
            "descripcion": "Moabita incorporada al pueblo de Dios y antepasada de David.",
            "aliases": ["Rut", "Ruth"],
        },
        {
            "palabra": "Ester",
            "hebreo": "\u05d0\u05e1\u05ea\u05e8",
            "transliteracion": "Ester",
            "significado": "Estrella; tambien asociado a ocultamiento.",
            "descripcion": "Reina usada para preservar a su pueblo.",
            "aliases": ["Ester", "Esther"],
        },
        {
            "palabra": "Job",
            "hebreo": "\u05d0\u05d9\u05d5\u05d1",
            "transliteracion": "Iyov",
            "significado": "Perseguido; objeto de enemistad.",
            "descripcion": "Hombre justo probado en sufrimiento.",
            "aliases": ["Job", "Iyov"],
        },
        {
            "palabra": "Jonas",
            "hebreo": "\u05d9\u05d5\u05e0\u05d4",
            "transliteracion": "Yonah",
            "significado": "Paloma.",
            "descripcion": "Profeta enviado a Ninive.",
            "aliases": ["Jonas", "Jonah", "Yonah"],
        },
        {
            "palabra": "Ninive",
            "hebreo": "\u05e0\u05d9\u05e0\u05d5\u05d4",
            "transliteracion": "Nineveh",
            "significado": "Morada de Ninus; significado discutido.",
            "descripcion": "Capital asiria a la que fue enviado Jonas.",
            "aliases": ["Ninive", "Nineve", "Nineveh"],
        },
        {
            "palabra": "Oseas",
            "hebreo": "\u05d4\u05d5\u05e9\u05e2",
            "transliteracion": "Hoshea",
            "significado": "Salvacion.",
            "descripcion": "Profeta menor cuyo nombre se relaciona con salvar.",
            "aliases": ["Oseas", "Hosea", "Hoshea"],
        },
        {
            "palabra": "Joel",
            "hebreo": "\u05d9\u05d5\u05d0\u05dc",
            "transliteracion": "Yoel",
            "significado": "Jehova es Dios.",
            "descripcion": "Profeta menor.",
            "aliases": ["Joel", "Yoel"],
        },
        {
            "palabra": "Amos",
            "hebreo": "\u05e2\u05de\u05d5\u05e1",
            "transliteracion": "Amos",
            "significado": "Carga; cargador.",
            "descripcion": "Profeta pastor de Tecoa.",
            "aliases": ["Amos"],
            "solo_mayuscula": True,
        },
        {
            "palabra": "Miqueas",
            "hebreo": "\u05de\u05d9\u05db\u05d4",
            "transliteracion": "Mikhah",
            "significado": "Quien como Jehova.",
            "descripcion": "Profeta menor con anuncio mesianico sobre Belen.",
            "aliases": ["Miqueas", "Micah", "Mikah"],
        },
        {
            "palabra": "Habacuc",
            "hebreo": "\u05d7\u05d1\u05e7\u05d5\u05e7",
            "transliteracion": "Javaqquq",
            "significado": "Abrazo; abrazador.",
            "descripcion": "Profeta menor que pregunta por la justicia de Dios.",
            "aliases": ["Habacuc", "Habakkuk"],
        },
        {
            "palabra": "Sofonias",
            "hebreo": "\u05e6\u05e4\u05e0\u05d9\u05d4",
            "transliteracion": "Tzefanyah",
            "significado": "Jehova esconde; Jehova protege.",
            "descripcion": "Profeta menor.",
            "aliases": ["Sofonias", "Zephaniah", "Tzefanyah"],
        },
        {
            "palabra": "Hageo",
            "hebreo": "\u05d7\u05d2\u05d9",
            "transliteracion": "Jaggai",
            "significado": "Festivo; de fiesta.",
            "descripcion": "Profeta de la reconstruccion del templo.",
            "aliases": ["Hageo", "Haggai", "Jaggai"],
        },
        {
            "palabra": "Esdras",
            "hebreo": "\u05e2\u05d6\u05e8\u05d0",
            "transliteracion": "Ezra",
            "significado": "Ayuda.",
            "descripcion": "Escriba y sacerdote del retorno del exilio.",
            "aliases": ["Esdras", "Ezra"],
        },
        {
            "palabra": "Nehemias",
            "hebreo": "\u05e0\u05d7\u05de\u05d9\u05d4",
            "transliteracion": "Nejemyah",
            "significado": "Jehova consuela.",
            "descripcion": "Lider en la reconstruccion de los muros de Jerusalen.",
            "aliases": ["Nehemias", "Nehemiah", "Nejemyah"],
        },
        {
            "palabra": "Mardoqueo",
            "hebreo": "\u05de\u05e8\u05d3\u05db\u05d9",
            "transliteracion": "Mordekhai",
            "significado": "Servidor de Marduk; significado persa/babilonico.",
            "descripcion": "Pariente de Ester en el exilio persa.",
            "aliases": ["Mardoqueo", "Mordecai", "Mordekhai"],
        },
    ]
)


DICCIONARIO_HEBREO.sort(key=lambda entrada: normalizar_palabra(entrada.get("palabra", "")))

_INDICE = {}
for entrada in DICCIONARIO_HEBREO:
    for alias in entrada.get("aliases", []):
        _INDICE[normalizar_palabra(alias)] = entrada


_PATRON_FRAGMENTOS = re.compile(r"[^\W\d_]+(?:[-'][^\W\d_]+)*|[^\w]+|\d+|_+")


def entradas_diccionario():
    return sorted(
        DICCIONARIO_HEBREO,
        key=lambda entrada: normalizar_palabra(entrada.get("palabra", "")),
    )


def entrada_para_palabra(palabra):
    entrada = _INDICE.get(normalizar_palabra(palabra))
    if entrada and entrada.get("solo_mayuscula"):
        texto = str(palabra or "").strip()
        if not texto[:1].isupper():
            return None
    return entrada


def fragmentos_con_diccionario(texto):
    for coincidencia in _PATRON_FRAGMENTOS.finditer(str(texto or "")):
        fragmento = coincidencia.group(0)
        yield fragmento, entrada_para_palabra(fragmento), coincidencia.start(), coincidencia.end()
